# Generated by Django 4.2.4 on 2023-08-30 13:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("railway_station", "0007_alter_trip_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 8, 30, 13, 1, 39, 822147, tzinfo=datetime.timezone.utc
                        )
                    )
                ]
            ),
        ),
    ]
