# Generated by Django 4.2.4 on 2023-08-30 13:09

from django.db import migrations, models
import railway_station.models


class Migration(migrations.Migration):
    dependencies = [
        ("railway_station", "0008_alter_trip_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=models.DateTimeField(
                validators=[railway_station.models.validate_departure_time]
            ),
        ),
    ]
