# Generated by Django 4.2.4 on 2023-09-04 08:07

from django.db import migrations, models
import railway_station.models


class Migration(migrations.Migration):
    dependencies = [
        ("railway_station", "0009_alter_trip_departure_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=railway_station.models.train_image_file_path
            ),
        ),
    ]
